print("Pertemuan Ketiga")
print("*"*20)

nama = input("Masukan Nama: ")
nim = input("Masukan NIM: ")
umur = input("Masukan Umur: ")
angkatan = input("Masukan Angkatan: ")

print("\n\n")
print("*"*20)
print("BIODATA SINGKAT")
print("*"*20)
print("NAMA \t\t: %s" % (nama))
print("NIM \t\t: %s" % (nim))
print("UMUR \t\t: %s" % (umur))
print("ANGKATAN \t: %s" % (angkatan))
